### ISSUE TITLE
Add student number in use check to new member form

### ISSUE THREAD

**Issue by nanderv** [Bellettrie/library_system#473]
Suggested implementation: strip the student-number of the 's', 'm', etc, and do a 'ends with' kind of check. When we switch to postgres we can add a custom index for this :).

**Comment by RemcoSwenker** [comment]
We can't distinguish between students and employees that way so we might get minor overlap with that. 
Do we want to block creation if we have a number collision?
Do we add a link to the member we have a number collision with?
