### ISSUE TITLE
Separate dms, blacklist, privacy form info and committees and current members filter forms using tabs

### ISSUE THREAD

**Issue by nanderv** [Bellettrie/library_system#562]
Currently all usecases for filtering members are handled with one piece of user interface, making it unwieldy and not always clear in what the combination of selected fields means.
For instance, the user can select a date+committee. But doing this results in getting everyone who was member on that date, and currently is in that committee.

As a concrete example when it goes wrong, the relationship between the selected filter date(s) blacklist status and DMS registration info is unclear, and indeed making the measurement date a singular date makes filtering the blacklist an imposssibility.

Given this, I'd suppose making the member filter page be multiple subpages, each on a separate tab within the page. The specific tab will then offer options related to that usecase.

Picture in an attempt to clarify:

![356d1060-b8eb-4301-bbc6-9b824911c35c.jpg](https://github.com/Bellettrie/library_system/assets/688987/356c4607-a69e-477f-acf4-74b917841b50)

Basically, we would get a few possible input forms: at least one for filtering current members, one for committee memberships, one for specials such as blacklist, dms, etc.
These forms get separate queries and separated pages, but can lean a lot on the same template, and reuse a lot of code.

Concrete suggested solution steps:
1. establish a base template that the subpages can inherit from, using a Django content block thingy for creating nice inheritance. Also use some variable for rendering the current tab.
2. Figure our a nice way to make the sub-urls
3. Rework the forms as separate subpage forms.
4. Write separate queries for the separate pages.

Observe that, if it fits within the url then using URL parameters may be nicer than a post request, since this means users can make bookmarks to a specific view.

**Comment by RemcoSwenker** [comment]
Plan seems legit Justen prefers that things on the same tab are the intersection of the choises
